### ISSUE TITLE
resolve crossrefs

### ISSUE THREAD

**Issue by timmli** [ge-ne/bibtool#12]
Is there a way to resolve crossref fields within entries, as done by  `bibexport -a`?

**Comment by ge-ne** [comment]
Yes, see documentation for resource expand.crossref

**Comment by timmli** [comment]
Thanks, works like a charm!
Where is it documented? I didn't find it here: http://ftp.uni-erlangen.de/ctan/biblio/bibtex/utils/bibtool/bibtool.pdf

**Comment by ge-ne** [comment]
It is documented in exactely this document. Take the time to carefully read it. It's worth it...and apologies -- sometimes you have to read a sentence twice and test it;-)
