### ISSUE TITLE
remove non-standard fields

### ISSUE THREAD

**Issue by timmli** [ge-ne/bibtool#13]
Is there a way to remove fields that don't belong to a predefined set? I would like to define a set of fields, e.g. {author,title,year,publisher}, and let BibTool remove any field that is not a member of this set. 

I'm dealing with large collections of BibTeX entries from various domains, and it's frightening how inventive scholars are. Therefore excluding non-standard fields one by one with `delete.field` is not an option.

**Comment by ge-ne** [comment]
Currently this can not be achieved within BibTool. I would create a script to collect the unwanted fields and write a BibTool resource to remove them.
I will consider this as feature request after the rewrite of the resource language

**Comment by timmli** [comment]
Thanks for your prompt reply. I'll think about an supplementary script then, but I'm looking forward to seeing this feature available in BibTool one day. Great work!

**Comment by ge-ne** [comment]
The new feature (keep.field) has been added to the development version in Git. It will make it into the next release.
