### ISSUE TITLE
having preserve.keys=on, bibtool -k does not regenerate keys for existing keys

### ISSUE THREAD

**Issue by grisuf** [ge-ne/bibtool#15]
By default key generation seems to be turned on as son as you have defined key.format. I would like to have my standard key.format in my ```~/.bibtoolsrc```. But if that is the case, even defined keys are overwritten by a normal bibtools-run. So I would be very happy if it would be possible to have key.format defined without having key generation turned on. That's why I defined key.format and turned off keygeneration by default in my ```~/.bibtoolsrc``` and thought that it would be possible to turn on keygeneration by ```bibtool -k```. ***Having ```preserve.keys=on``` in ```~/.bibtoolsrc```, ```bibtool -k``` does not regenerate keys for existing keys.*** To demontrate the behavior I wrote a little minimal-example in bash (not using ```~/.bibtoolsrc```, because I don't want to overwrite yours). Have you got an solution for my problem?
 
```sh
#!/bin/bash
rsc=$(tempfile -s .rsc)

bib="@book{key,
author={Hans Christian Andersen},
title={Das hässliche Entlein},
year={1843}}"

echo $bib | bibtool -r $rsc

echo "I want to define my key.format in my main ~/.bibtoolsrc. For
demonstration purposes, I define it in a temporary rsc-file. I didn't expect
that definition to turn on key-generation."

echo 'key.format="%-1n(author)%n(year)%-W(title)"'>$rsc

echo -e "\n\nThe definition of key.format seems to turn on key-generation:"
echo $bib | bibtool -r $rsc

echo -e "\n\nSo I add preserve.keys, so that I don't overwrite existing keys"
echo 'preserve.keys=on'>>$rsc
echo $bib | bibtool -r $rsc

echo -e "\n\nBut sometimes I need to overwrite existing keys, so I add -k to
bibtool and expect it to do the key-generation. But that doesn't happen."
echo $bib -k| bibtool -r $rsc

echo "How can I define my key.format in the main ~/.bibtoolsrc keeping the 
default behavior of key-generation?"

rm $rsc
```

**Comment by ge-ne** [comment]
The behaviour described can be explained as follows:

- First the command line arguments are evaluated
- The option -k simply sets a resource for the format to "short"
- Afterwards the default resource file is read *if* required, i.e. no other resource has been loaded before
- The later setting of resources overwrite the earlier ones

Thus a solution would be to manually reverse the order. This can be done with a shell script (called bibtool) which invokes BibTool and provides as first action on the command line -r ~/.bibtoolrsc
With this script on the PATH before the original executable it is invoked and the command line arguments overwrite the settings -- as requested.

**Comment by grisuf** [comment]
thanks!
