### ISSUE TITLE
umlauts to ascii in key

### ISSUE THREAD

**Issue by grisuf** [ge-ne/bibtool#16]
Having a bibtex-entry like
```
@book{,
  title         = {Übertreibungen in Richtung Wahrheit. Stenogramme, Glossen, Aphorismen},
  editor        = {Lütkehaus, Ludger},
  author        = {Anders, Günther},
  year          = {2002},
  publisher     = {C.H. Beck},
  address       = {München},
  isbn          = {3-406-47612-0},
}
```
The citation key is built by
```
key.format="{%-1n(author)#%-1n(editor)}{%n(year)#%n(date)}{%-W(title)}"
```
and outputs correctly günther2002übertreibungen. How do I get a ascii citation key (guenther2002ueberlegungen)?

**Comment by ge-ne** [comment]
See BibTool Manual section A.10.9

**Comment by grisuf** [comment]
So I did some 
```
tex.define {ü=ue}
```
but that does also change the rest of the output and I did not find a way to restrict the conversion to the bibtex-key.
