### ISSUE TITLE
please consider to mention distributions

### ISSUE THREAD

**Issue by jgmbenoit** [ge-ne/bibtool#20]
In the installation instructions present in the documentation (e.g., README.md, install.tex), please mention that bibtool has been packaged for a couple of distributions (e.g., Debian based distributions as Ubuntu), so that potential users can consider to install the bibtool package effectively distributed by their favourite distribution before installing from the upstream source. This is certain the best for every one: the upstream maintainer, the packages maintainers, and the final users.

**Comment by ge-ne** [comment]
Done
