### ISSUE TITLE
please consider to provide a ld-version-script

### ISSUE THREAD

**Issue by jgmbenoit** [ge-ne/bibtool#21]
Is it possible to provide an official ld-version-script for the libtool library ?
For ld-version-script information, a goot start is provided in the GNULib documentation:
https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html

**Comment by ge-ne** [comment]
I havn't got the idea. What should this script contain? 
Dependencies: BibTool has none
Something for a shared object: BibTool is a stand-along program

I am willing to include something into the distibution as soon as I understand it...

**Comment by jgmbenoit** [comment]
A version-script (or a map) of a library is meant to contains the symbols that the library exports. It is not clear to me whether or not BibTools may come with a library support in view to write interfaces built with it. It makes sense. Whatever. I am asking because I see a `c_lib.pdf' file around,i.e., ``Documentation of the C interface in PDF format''. So I assume that there is an API/ABI around as well. I have also noticed that the Debian packages used to bring a -dev package.

**Comment by ge-ne** [comment]
Ah, I see. Yes, BibTool was developed with an API in mind. This is documented in the PDF and used in the Tcl binding which is included in BibTool. I am currently using the same API to test the upcoming new features.
I will have to look into this to find out how to write and test such a file...

**Comment by ge-ne** [comment]
A ld-library-script is included in the distribution. I still have not used it yet.
