### ISSUE TITLE
Please provide material to perform stresstests

### ISSUE THREAD

**Issue by jgmbenoit** [ge-ne/bibtool#23]
Are any kind of stresstest performed during development ? If so, would it be possible to provide it within the upstream source tarball ?

**Comment by ge-ne** [comment]
BibTool comes with a test suite which is packaged in the sub-directory test. The tests can be run with the command
make test
That'*s what I do during development and in the process of preparing a distribution.
There could be more tests. I add some whenever a bug turns up.

**Comment by jgmbenoit** [comment]
I was dealing with stresstests: I have an heavy, intricate data inputs.

**Comment by ge-ne** [comment]
The BibTeX format is not intricate and all cases I have thought of are covered in the test cases.
I do not have anything else that I am able to include into the distribution.

**Comment by jgmbenoit** [comment]
No offence: by intricate I mean something that can challenge bibtool.
If you have no such material in hand: it is ok (of course), and it is good to know.
Thanks for the precisions.
