### ISSUE TITLE
Missing file io.h.

### ISSUE THREAD

**Issue by stefanhusmann** [ge-ne/bibtool#24]
The compilation fails with

```
gcc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2  -Iinclude  -DREGEX -Iregex-0.12 -I.. -DHAVE_LIBKPATHSEA -c main.c
main.c:81:24: schwerwiegender Fehler: bibtool/io.h: Datei oder Verzeichnis nicht gefunden
```
and indeed that file is missing in bibtool/include/bibtool.

**Comment by ge-ne** [comment]
Sorry, you have hit Github in the middle of a refactoring today. I have provided the missing file now. 
I will have to investigate why git has ignored this file before.

**Comment by stefanhusmann** [comment]
No problem, thanks.
