### ISSUE TITLE
key.c: null not declared

### ISSUE THREAD

**Issue by stefanhusmann** [ge-ne/bibtool#32]
key.c:255:12: Fehler: »null« nicht deklariert (erste Benutzung in dieser Funktion)
     return null;       /*        */
            ^~~~
key.c:255:12: Anmerkung: jeder nicht deklarierte Bezeichner wird nur einmal für jede Funk
ion, in der er vorkommt, gemeldet
make: *** [makefile:487: key.o] Fehler 1

Having
#define null ((void*)0)' key.c
fixes it.

**Comment by ge-ne** [comment]
Thanks for the report.
I have fixed it (differently).
