### ISSUE TITLE
The current PDF file on the main BibTool webpage is broken

### ISSUE THREAD

**Issue by cviner** [ge-ne/bibtool#34]
The current PDF file uploaded to the main BibTool webpage (at http://www.gerd-neugebauer.de/software/TeX/BibTool/bibtool.pdf) appears to be missing (the link refers to a zero-byte file). I am, however, still able to access the manual from [CTAN](http://ctan.math.utah.edu/ctan/tex-archive/biblio/bibtex/utils/bibtool/bibtool.pdf).

**Comment by ge-ne** [comment]
I have troubles with my ISP at the moment. Thus you should use CTAN or GitHub as alternatives.

Sorry for any inconvenience.

**Comment by cviner** [comment]
No problem; I just wanted to make sure that you were aware of it. Thanks.
