### ISSUE TITLE
biblatex.rsc results in errors

### ISSUE THREAD

**Issue by chneukirchen** [ge-ne/bibtool#35]
Since 5fc54f22002d, biblatex support is broken:

```
*** BibTool WARNING: Unknown entry type `suppollection'. Mapping ignored.

{article subperiodical} journaltitle = periodical
_________________________________________________^
*** BibTool ERROR: Symbol expected.

}
_^
*** BibTool WARNING:  (line 298 in /tmp/bibtool/lib/biblatex.rsc): Symbol does not start with a letter
```

Used command line `BIBTOOL=$PWD/lib ./bibtool -r biblatex -i ~/phd/own.bib -o foo.bib`

Also, why does biblatex.rsc define capitalized key names? The current BibLaTeX manual uses lowercase ones, perhaps that changed at some point.

**Comment by ge-ne** [comment]
Thanks for the report
I have fixed the file and comitted to the repository. It will make it into the next release.
Sorry for any inconvenience.

Regarding capitalized key names:
I have copied the cased keys from some source. I don't remember from where.
You can easily take the resource file and make a variant biblatex-lc.rsc which fits your expectations.
