### ISSUE TITLE
comment triggers BibTool ERROR: Symbol expected

### ISSUE THREAD

**Issue by timmli** [ge-ne/bibtool#37]
Tested on version 2.61 (Cygwin):
If I put a comment inside a construct that spans several lines, `BibTool ERROR: Symbol expected` is thrown.

Example:
```
sort.order{* =           % * is the wildcard for entry types
	 author
	#sortkey
	#title
	}
```

Bug or feature?

**Comment by ge-ne** [comment]
% is no comment character as in TeX. Thus leaving out the comment after = leads to a legal resource instruction.
If you want to comment it you can do it _before_ sort.order or after the instruction is complete.

**Comment by timmli** [comment]
Why not treat % the usual way? This is confusing. 
Could you then please make the error message more informative? With big files, it takes some time to figure out what the problem is ...

Thanks!

**Comment by ge-ne** [comment]
The behavior is documented in the BibTool Manual on page 20. The new parser for BibTool 3 might bring an improvement.
I have improved the error message. It will make it into the next release. Meanwhile it's in the repository.
