### ISSUE TITLE
Remove old style font commands

### ISSUE THREAD

**Issue by mjg** [ge-ne/bibtool#38]
Old style font commands (`\bf, \it, \sc, \tt, \rm`) have been deprecated for years. Several packages have dropped support for them now, most notably the KOMA classes. As a result, `doc/c_lib.tex` cannot be compiled with current TeXlive any more, at least not without adding the `enabledeprecatedfontcommands` option (which is only a band aid).

`BibTcl/bibtcl.tex` and `doc/ref_card.tex` contain old style font commands, as well, but they don't use KOMA classes so that they still compile.

So please remove old style font commands where necessary, or better: everywhere :)

[This is part of getting the BibTool package to build again on Fedora 25 with the updated, current TeXlive.]

**Comment by ge-ne** [comment]
It should be fixed in the repository. It will make it into the next release -- presumably in January.
