### ISSUE TITLE
empty separators cause an error

### ISSUE THREAD

**Issue by jgmbenoit** [ge-ne/bibtool#39]
debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848947
[bureport-848947.zip](https://github.com/ge-ne/bibtool/files/673212/bureport-848947.zip)

**Comment by ge-ne** [comment]
I have fixed the bug and added tests. The changes are in the reporsitory and will make it into the January release.

**Comment by jgmbenoit** [comment]
Thanks for your prompt reaction. I noted that you will make a new release in January. Nevertheless, because during the Debian freezing we must react quickly, I already brought the fix to Debian.

**Comment by gi1242** [comment]
Thanks for fixing this quickly, and pulling the fix into Debian. If the fix hadn't made it into the Debian freeze I'd be stuck with this for a long time!
