### ISSUE TITLE
key formatting differs between 2.55 and 2.56

### ISSUE THREAD

**Issue by danielbruns** [ge-ne/bibtool#4]
The format of generated keys seems to differ between versions 2.55 and 2.56: suffixes added for disambiguity start from "b" in 2.55 and from "a" in 2.56. Is there a way to enforce the old behavior?

I'm working on a book with c. 20 other authors and each uses a different version of bibtool. This makes it infeasible that everyone upgrades.

**Comment by ge-ne** [comment]
> 
>     On 22 January 2015 at 12:34 danielbruns <notifications@github.com> wrote:
> 

Hi,

> 
>     The format of generated keys seems to differ between versions 2.55 and
> 2.56: suffixes added for disambiguity start from "b" in 2.55 and from "a" in
> 2.56. Is there a way to enforce the old behavior?
> 


the changelog contains an entry about this saying that this is bugfix. The
program differs from the specification (i.e. documentation).

Currently there is no backward-compatibility mode for bugfixes.

If you can live with the consequences I recomment to downgrade to 2.55:-(


> 
>     I'm working on a book with c. 20 other authors and each uses a different
> version of bibtool. This makes it infeasible that everyone upgrades.
>     —
>     Reply to this email directly or view it on GitHub.
> 


Ciao

Gerd
