### ISSUE TITLE
Check required fields

### ISSUE THREAD

**Issue by eliasm** [ge-ne/bibtool#40]
I might be looking for the wrong keywords, but I could not find an option to check the required fields for each entry (e.g., `author, title, journal, year` for `@article`). Is there a way to do this with bibtool?

**Comment by ge-ne** [comment]
The required fields heavily depend on the BbTeX style you are using. There are complicated rules in there. For instance for a @book you need an author _or_ an editor. Thus it would be best to leave this task to BibTeX.
Nevertheless, you might want to have a look at the libraries field.rsc, keep_bibtex.rsc, and biblatex.rsc in the BibTool lib/ directory. Maybe you will find inspirations which you will consider useful.

**Comment by kiryph** [comment]
Would it be possible to add a new resource `required.field` similar to `keep.field` so a user can define what fields the bibtex records should have?

It could look like
```
required.field {{author
	     title
	     journal
	     year
	     volume
	     number
	     pages
	     month}
  if $type = article}
```

**Comment by kiryph** [comment]
Thanks for your answer.

### Clarfication what `key` refers to

Most of your mentioned examples could have a `key` as alternative.  What do you refer to by key?


### Perfection is not necessary

I meant to give the user the possibility to define what the bib records in her/his situation should have. The situation depends on the type of document, requirements by the publisher or university, etc. Also some personal fields could be of interest to see whether all records have them such as `annotation`, `file`, `image`, etc.


Maybe there are either-or cases which might not (yet) be supported.  But there are plenty of situations where you want to make sure that entries have certain fields which would make this already useful.

In general using linter-like tools is usually not perfect but still can be helpful to spot early on missing data/issues. Better than waiting for a long-compilation run until bibtex/biber complains.

### Existing feature in other tools

I just want to make some references that there is interest in this feature and there exist implementations:

Answers to the question [How to validate (check) a biblatex .bib file?](https://tex.stackexchange.com/q/173621/8917) on tex.stackexchange.com refer to other tools which can already help

- [biblatex-check](https://github.com/pezmc/biblatex-check) (no longer under active development)
- [jabref](http://www.jabref.org/) (gui, not suitable as a linter)


There are two tools which try to automate this:

- [betterbib](https://github.com/nschloe/betterbib#readme) tries to fetch missing data from the internet
- [bibcure](https://github.com/bibcure/bibcure#readme) (beta) completes all fields(url, journal, etc) of all bib items using DOI number (requires internet connection)


Automatically fetching data from the internet is nice but there might be reasons that you want to use your own local data which could disagree with the online data. Also if there is no doi, bibcure cannot help.

Therefore I see a reason why bibtool could have this feature with manual configuration.
