### ISSUE TITLE
makeindex instead of makeidx?

### ISSUE THREAD

**Issue by dbitouze** [ge-ne/bibtool#43]
I guess the index engine in https://github.com/ge-ne/bibtool/blob/master/INSTALL should be `makeindex`  instead of `makeidx`

**Comment by ge-ne** [comment]
> On 19 February 2018 at 10:06 Denis Bitouzé <notifications@github.com> wrote:
> 
> 
>     I guess the index engine in https://github.com/ge-ne/bibtool/blob/master/INSTALL should be makeindex instead of makeidx
> 


Thanks for the hint. In fact there is a disclaimer in the INSTALL file that the executable may be named differently.

Neverthemess I have changed the name...for the next release.


Ciao

Gerd
