### ISSUE TITLE
Problem extracting entries using -x

### ISSUE THREAD

**Issue by sbecuwe** [ge-ne/bibtool#49]
Hello, 

it seems I'm not able to extract entries. `bibtool -x t.aux` simply doesn't do anything, with or without the `-o` option. Any idea?

Kind regards
Stefan

**Comment by ge-ne** [comment]
Does the aux file contain \citation, \bibdata and/or \@import statements?
The analysis tries to find those macros as they are prodced by BibTeX...

**Comment by sbecuwe** [comment]
Both \citation and \bibdata are present. See attached files.
I get following warning:
`$ bibtool -x dummy.aux`
`*** BibTool WARNING: File bibcite not found.`
which is strange since the bib file is mentioned in \bibdata.


[dummy.zip](https://github.com/ge-ne/bibtool/files/2475251/dummy.zip)

**Comment by ge-ne** [comment]
I have fixed this nasty little bug in the memory management. It is on Gihub and will make it into the next release.
