### ISSUE TITLE
Missing file bibtool.tex

### ISSUE THREAD

**Issue by stefanhusmann** [ge-ne/bibtool#5]
The tarball under http://www.gerd-neugebauer.de/software/TeX/BibTool/BibTool-2.58.tar.gz does not include bibtool.tex, but a symlink to it, that points to nowhere.

**Comment by ge-ne** [comment]
> On 11 February 2015 at 20:49 Stefan Husmann <notifications@github.com> wrote:

> The tarball under
> http://www.gerd-neugebauer.de/software/TeX/BibTool/BibTool-2.58.tar.gz does
> not include bibtool.tex, but a symlink to it, that points to nowhere.

Thanks for the report. I can see what appears to be something like a link.
Nevertheless I have no link in my sources.

I have replaced the tar ball with a pressumably better incarnation. Could you
please check.

Thanks
Gerd

**Comment by stefanhusmann** [comment]
S
It turns out this seems to be a problem with bsdtar. bsdtar -tvf shows me 
hrw-r--r--  0 gene   gene        0 Feb  9 20:22 BibTool/doc/bibtool.tex link to BibTool/doc/bibtool.tex
and, whth x instead of t, fails with "bsdtar: Error exit delayed from previous errors.
gnu tar shows a similar output
hrw-r--r-- gene/gene         0 2015-02-09 20:22 BibTool/doc/bibtool.tex Verknüpfung zu BibTool/doc/bibtool.tex
but does not fail. Strange, I never saw this before, especially not with older versions of bibtool. I want to package this for Arch Linux, and our package manager uses bsdtar, not gnu tar, to unpack tarballs. 

The file I download has 704506 bytes and the md5sum is 138cea71a2af8e5aec301b0cfc69f8a3 (and did not change, so maybe it is still the old one).

**Comment by ge-ne** [comment]
> On 11 February 2015 at 22:24 Stefan Husmann <notifications@github.com> wrote:

>  It turns out this seems to be a problem with bsdtar. bsdtar -tvf shows me 
>  hrw-r--r-- 0 gene gene 0 Feb 9 20:22 BibTool/doc/bibtool.tex link to
> BibTool/doc/bibtool.tex
>  and, whth x instead of t, fails with "bsdtar: Error exit delayed from
> previous errors.
>  gnu tar shows a similar output
>  hrw-r--r-- gene/gene 0 2015-02-09 20:22 BibTool/doc/bibtool.tex Verknüpfung
> zu BibTool/doc/bibtool.tex
>  but does not fail. Strange, I never saw this before, especially not with
> older versions of bibtool. I want to package this for Arch Linux, and our
> package manager uses bsdtar, not gnu tar, to unpack tarballs.

I am doing the same all the time. I have a makefile to package a distribution...

> The file I download has 704506 bytes and the md5sum is
> 138cea71a2af8e5aec301b0cfc69f8a3 (and did not change, so maybe it is still the
> old one).

In any case you can take the file from github. Version 2.58 is tagged (and I
havn't changed anything since)

Ciao
Gerd

**Comment by stefanhusmann** [comment]
Yes that one works fine. Thanks.
