### ISSUE TITLE
How to use this software? (Make a video)

### ISSUE THREAD

**Issue by sanaptejas** [ge-ne/bibtool#51]
It would be really nice (and, easy) if you could make a video that shows what can be done with this software and how to do it. This is a kind suggestion (and, a hopeful request). Thank you.

**Comment by ge-ne** [comment]
I am more a writer and less an actor. Thus I fear that getting things started would mean quite an amount of work for me:-(

**Comment by sanaptejas** [comment]
Okay. Thanks, anyways.
