### ISSUE TITLE
Extend duplicate detection

### ISSUE THREAD

**Issue by kiryph** [ge-ne/bibtool#54]
Bibtool considers two records as duplicates in following circumstance

> Ad 2: See resource check.double.
Double entries are identified if their sort key is identical.
https://github.com/ge-ne/bibtool/issues/50#issuecomment-441832506

Would it be possible to add additional warnings, if two records have the same

- bibkey (useful when the sorting is customized or sorting is not enabled), or
- doi number
- arxiv id

The doi number check could be added to the default duplicate detection with the auto fix capabilities of bibtool (deactivate with ### or delete record).
A duplicate bibkey can also mean the user has chosen the same bibkey for different records and therfore the bibkey must be renamed but surely the record should not be deleted.

These additions would also increase the usefulness of bibtool as a linting tool as asked int #52 .

**Comment by kiryph** [comment]
Thank you for your recent updates including 41203971c2d130052302cf7a94fc5e77545be2fd.

1. However, I think there is a regression:
```
❯ cat my.bib
@article{Koch:1984,
  author  = {Koch, E.},
  doi     = {10.1107/S0108767384001227},
  issn    = {0108-7673},
  journal = {Acta Crystallographica Section A Foundations of Crystallography},
  month   = {sep},
  number  = {5},
  pages   = {593--600},
  title   = {{The implications of normalizers on group–subgroup relations between space groups}},
  volume  = {40},
  year    = {1984}
}
@Article{Dove:1997,
  author  = {Dove, Martin T.},
  title   = {{Theory of displacive phase transitions in minerals}},
  doi     = {10.2138/am-1997-3-401},
  issn    = {0003-004X},
  journal = {American Mineralogist}
  month   = {apr},
  number  = {3-4},
  pages   = {213--244},
  url     = {https://pubs.geoscienceworld.org/ammin/article/82/3-4/213-244/43266},
  volume  = {82},
  year    = {1997}
}
@article{Koch:1984,
  author  = {Koch, E.},
  doi     = {10.1107/S0108767384001227},
  issn    = {0108-7673},
  journal = {Acta Crystallographica Section A Foundations of Crystallography},
  month   = {sep},
  number  = {5},
  pages   = {593--600},
  title   = {{The implications of normalizers on group–subgroup relations between space groups}},
  volume  = {40},
  year    = {1984}
}

❯ cat bibtoolrsc
check.double = on
sort         = on
sort.format  = { doi }

❯ /usr/local/Cellar/bib-tool/HEAD-4120397/bin/bibtool -r bibtoolrsc ~/my.bib
*** BibTool WARNING (line 26 in /Users/kiryph/my.bib): Possible double entry discovered to (line 13 in /Users/kiryph/my.bib) `dove:1997'
*** BibTool WARNING (line 26 in /Users/kiryph/my.bib): Possible double entry discovered to (line 1 in /Users/kiryph/my.bib) `koch:1984'
*** BibTool WARNING (line 13 in /Users/kiryph/my.bib): Possible double entry discovered to (line 1 in /Users/kiryph/my.bib) `koch:1984'

@Article{	  koch:1984,
  author	= {Koch, E.},
  doi		= {10.1107/S0108767384001227},
  issn		= {0108-7673},
  journal	= {Acta Crystallographica Section A Foundations of
		  Crystallography},
  month		= {sep},
  number	= {5},
  pages		= {593--600},
  title		= {{The implications of normalizers on group–subgroup
		  relations between space groups}},
  volume	= {40},
  year		= {1984}
}

###Article{	  dove:1997,
  author	= {Dove, Martin T.},
  title		= {{Theory of displacive phase transitions in minerals}},
  doi		= {10.2138/am-1997-3-401},
  issn		= {0003-004X},
  journal	= {American Mineralogist},
  month		= {apr},
  number	= {3-4},
  pages		= {213--244},
  url		= {https://pubs.geoscienceworld.org/ammin/article/82/3-4/213-244/43266},
  volume	= {82},
  year		= {1997}
}

###Article{	  koch:1984,
  author	= {Koch, E.},
  doi		= {10.1107/S0108767384001227},
  issn		= {0108-7673},
  journal	= {Acta Crystallographica Section A Foundations of
		  Crystallography},
  month		= {sep},
  number	= {5},
  pages		= {593--600},
  title		= {{The implications of normalizers on group–subgroup
		  relations between space groups}},
  volume	= {40},
  year		= {1984}
}
```
The entry `dove:1997` should not be detected as a duplicate (different doi and bibkey).
Maybe the message could mention the reason for the duplicate detection.

2. I am also wondering whether it is possible to sort according to doi to get a warning for duplicate dois, but also an error for duplicate bibkeys?

**Comment by ge-ne** [comment]
> sort.format  = { doi }

This means that each record has the same constant sort.format, i.e. "doi". If you want to compare for the field use something like sort.format  = { %s(doi) }

> I am also wondering whether it is possible to sort according to doi to get a warning for duplicate dois, but also an error for duplicate bibkeys?

I am thinking about having several formats for different equality criteria.

**Comment by ge-ne** [comment]
resource unique.field has been introduced for this purpose

**Comment by kiryph** [comment]
I have one thought about the last sentence in following item recently added to Changes.tex (41203971c2d130052302cf7a94fc5e77545be2fd) regarding the speed of bibtool

> - The behaviour of the resource \rsc{check.double} has been
    generalized. The requirement that double entries to be adjacent
    has been dropped. This has the impact that the processing is
    slightly slower.

I think when bibtool is run with the option `-q` (quiet), the runtime should not be affected by the extended duplicate check.

**Comment by ge-ne** [comment]
> I think when bibtool is run with the option -q (quiet), the runtime should not be affected by the extended duplicate check.

Unfortunately this is not true. The processing of duplicates (deleting or marking) has to happen in any case.

The complexity of the algorithm has been O(n) and is now something like O(n log(n)). But I am not worried. The processing speed of up-to-date computers should be sufficient for realistic databases.

**Comment by kiryph** [comment]
> The processing of duplicates (deleting or marking) has to happen in any case.

I think I was not specific enough: I meant when run without `-d`. Is this still true?

However, I agree the speed of bibtool is nothing I am worried about too. People writing articles, theses or books should have less than 10.000 entries should not notice anything. Maybe other people with different usage scenarios such as webscraping millions of bibliographic records.

**Comment by kiryph** [comment]
The feature

> resource unique.field

is really what I had in mind. Thank you very much for adding it (f02e49616ee097e6cec8d08ba084467feb3e3f3b).
