### ISSUE TITLE
get crufty bibtex into shape for biblatex

### ISSUE THREAD

**Issue by j2bryson** [ge-ne/bibtool#60]
Hi, thanks for your tool!

I ordinarily keep all kinds of notes and part-formed bibtex in the file where all my real bibtex also lives. This is no problem with bibtex itself, but kills about everything else that uses a bibtex file.

Your tool successfully parses my entire file, but the output it generates still makes biblatex barf.  On the other hand, if I could just extract the entries mentioned in my aux file, probably those would not make biblatex barf. But not everything mentioned in my .aux file exists, because I also am used to using bibtex to remind me when I need to dig up citations I don't already have, so it tells me what labels I made up while I was writing.

One of the attached files is the .bib from running your program that generates an "abort trap 6" on a mac in biblatex, the other is a .aux that throttles your program, git is making me rename them both .txt but I think it's not hard to see which is which
[biblatex-jun19.txt](https://github.com/ge-ne/bibtool/files/3340442/biblatex-jun19.txt)
[AIforLawofAI.txt](https://github.com/ge-ne/bibtool/files/3340444/AIforLawofAI.txt)

**Comment by j2bryson** [comment]
PS please delete these files after you've played with them, I wouldn't want all the comments I've made on people's articles shared forever...

**Comment by j2bryson** [comment]
One of the guys who maintains biblatex says "  It looks like an encoding issue - for example, my Emacs isn’t able to work out the encoding of the file and default to a raw multi-byte as it looks like it’s been a bit mangled, perhaps by bibtool. In general, all quotes, dashes etc. look like they have been decoded twice into raw byte triples and so biber can’t read it in the default utf8 setting and I can’t work out what other setting would work. 
"

**Comment by ge-ne** [comment]
Well, BibTool does not play around with encodings. It reads the file byte by byte and outputs byte by byte.

I am not sure what you expect me to do. I can dig around in BibTool, But I need exact iformation what you are doing and what you are expecting and a _minimal_ example...
