### ISSUE TITLE
values surrounded by double pairs of braces not parsed correctly (bug?)

### ISSUE THREAD

**Issue by herrsimon** [ge-ne/bibtool#61]
When enclosing a field-value in double pairs of curly braces (to prevent BibTeX to adjust any capitalization), bibtool seems to no longer parse the value correctly. For example, if a bibtex-entry contains the field

```
title = {{Some title with an acronym like MCMC}}
```

then `%-3.0T(title)` will always return the whole title instead of only the first three words.

Of course one could change the above line to

```
title = {Some title with an acronym like {MCMC}}
```

so that bibtool again parses correctly, but this would be very inconvenient and time-consuming when entries are obtained automatically from a database (in my case zbmath.org, which always surrounds the fields `title`, `journal` and `fjournal` by double pairs of braces).

Could you please change the behaviour of bibtool so that such double pairs are recognized and the enclosed values parsed correctly?

**Comment by ge-ne** [comment]
The behaviour of BibTool is correct wrt the semantics of BibTeX. Curly braces enclose a block which is treated as one word. Thus capitalization does not change anything inside.

Double curly braces is a dirty hack. To preserve the case only the acronyms should be enclosed or a BibTeX style should be used which does not alter capitalization.

In general I will not support the notion of double curly braces. But I could imagine to add a cleanup function to push curly braces inwards to surround words with capital letters only.

BTW zbmath.org does it correctly for the author field. Maybe a bug report there would be better to tackle the problem at its source...

**Comment by herrsimon** [comment]
I already have such a cleanup function in place for zbmath.org and thanks to your reply it makes no perfect sense to me not to alter anything in bibtool. Thanks a lot for the clarification and the quick reply!
Ps: I have filed a bug report at zmbath.org but doubt that they will change anything
