### ISSUE TITLE
bug: bibtool crashes when custom field contains %t(title)

### ISSUE THREAD

**Issue by herrsimon** [ge-ne/bibtool#63]
Hello again, 

I observed a strange bibtool crash when custom field contains a `%t(title)` formatting instruction. In the following a minimal example. File `test.rsc`:

```
new.field.type {test}
add.field { test="%t(title)" }
```

File `input.bib`:

```
@InCollection{ key,
  series = {Testseries},
  title = {Testtitle},
  author = {Muster, Max},
  editor = {Doe, John},
  year = {1985},
  pages = {1--10},
}
```

Output of `bibtool -v -r test.rsc -i input.bib -o output.bib`:

```
--- BibTool: Trying ./test.rsc
--- BibTool: Set resource new.field.type = test
--- BibTool: Set resource add.field =  test="%-0.0t(title)" 
--- BibTool: Reading input.bib
+--- BibTool: Done with input.bib
[1]    3458803 segmentation fault (core dumped)  bibtool -v -r test.rsc -i input.bib -o output.bib
```

However, as soon as I add one of the lines `fmt.name.title={_}` or `fmt.title.title={_}` to `test.rsc`, the error disappears.

**Comment by ge-ne** [comment]
The problem was a missing lacy initialization. I have fixed the problem and pushed it to the head revision.

**Comment by herrsimon** [comment]
perfect, thanks a lot!
