### ISSUE TITLE
Support Windows with MSYS2

### ISSUE THREAD

**Issue by fleimgruber** [ge-ne/bibtool#65]
I have been able to compile bibtool using MSYS2 sometime last year. Are there any plans to support MSYS2 on Windows properly? I tried with latest bibtool and latest MSYS2 tools and did

```
mv makefile.unx makefile
./configure
make
```

and the full output of that is

```
$ make
gcc -g -O2   -Iinclude  -DREGEX -Iregex-0.12 -I..  -c main.c
gcc -g -O2   -Iinclude  -c -c check.c -o check.o
gcc -g -O2   -Iinclude  -c -c crossref.c -o crossref.o
crossref.c: In function 'map_add':
crossref.c:117:4: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  117 |   ((long)(SF) & 0xfff) +    \
      |    ^
crossref.c:157:9: note: in expansion of macro 'MAP_INDEX'
  157 |   idx = MAP_INDEX(s_rec, s_fld, d_rec);     /*                        */
      |         ^~~~~~~~~
crossref.c: In function 'map_get':
crossref.c:117:4: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  117 |   ((long)(SF) & 0xfff) +    \
      |    ^
crossref.c:194:11: note: in expansion of macro 'MAP_INDEX'
  194 | { int i = MAP_INDEX(s_rec, s_fld, d_rec);    /*                        */
      |           ^~~~~~~~~
gcc -g -O2   -Iinclude  -c -c database.c -o database.o
gcc -g -O2   -Iinclude  -c -c entry.c -o entry.o
gcc -g -O2   -Iinclude  -c -c error.c -o error.o
gcc -g -O2   -Iinclude  -c -c expand.c -o expand.o
gcc -g -O2   -Iinclude   -c init.c
gcc -g -O2   -Iinclude  -c -c io.c -o io.o
gcc -g -O2   -Iinclude  -c -c key.c -o key.o
gcc -g -O2   -Iinclude  -c -c macros.c -o macros.o
gcc -g -O2   -Iinclude  -c -c names.c -o names.o
gcc -g -O2   -Iinclude   -c parse.c -o parse.o
gcc -g -O2   -Iinclude  -c -c print.c -o print.o
gcc -g -O2   -Iinclude  -c -c pxfile.c -o pxfile.o
gcc -g -O2   -Iinclude  -c -c record.c -o record.o
gcc -g -O2   -Iinclude  -DREGEX -Iregex-0.12 -I.. -c rewrite.c -o rewrite.o
rewrite.c: In function 'dont_keep':
rewrite.c:904:18: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  904 |   intptr_t idx = (int)(sym) % K_RULES_SIZE;    /*                        */
      |                  ^
gcc -g -O2   -Iinclude  -DRSC_BIBINPUTS_DEFAULT=NULL -DRSC_BIBTOOL_DEFAULT=\".:/mingw64/lib/BibTool\" -DENV_SEP=\":\" -c rsc.c -o rsc.o
In file included from rsc.c:56:
include/bibtool/rsc.h:56:60: error: incomplete universal character name \U
   56 | DECLARE( String, rsc_v_rsc , (String)(RSC_BIBTOOL_DEFAULT) );
      |                                                            ^
include/bibtool/rsc.h:56:60: warning: unknown escape sequence: '\L'
include/bibtool/rsc.h:56:60: warning: unknown escape sequence: '\o'
include/bibtool/rsc.h:56:60: warning: unknown escape sequence: '\m'
include/bibtool/rsc.h:56:60: warning: unknown escape sequence: '\m'
include/bibtool/rsc.h:56:60: warning: unknown escape sequence: '\l'
include/bibtool/rsc.h:56:60: warning: unknown escape sequence: '\B'
make: *** [makefile:489: rsc.o] Error 1
```

where for me the most likely culprit for "error: incomplete universal character name \U" is a Windows path string that starts with "C:\Users\user\...", e.g. not properly escaped ("\\" -> "\\\\"). Any ideas?

**Comment by ge-ne** [comment]
> Are there any plans to support MSYS2 on Windows properly?

I'd like to support BibTool for as many systems as possible. I have no MSYS2 system at hand. Thus I rely on help by others.

>    56 | DECLARE( String, rsc_v_rsc , (String)(RSC_BIBTOOL_DEFAULT) );

The makefile takes some values from the during the compilation defined environment. RSC_BIBTOOL_DEFAULT is populated from the environment variable BIBTOOL_DEFAULT. You should have a look at this and other environment variables starting with BIBTOOL

**Comment by fleimgruber** [comment]
Ok, I don't know yet how to actually debug this, but I will try with what I have right now and thinking. I might have a lead here since the concrete order of unknown escape sequences (`\U, \L, \o, \m, \m, \l, \B`) maps nicely to `C:\Users\L...\opt\msys64\mingw64\lib\B(ibtool)` (presumably) which AFAIK is the `lib\...` for the msys2 64 bit MinGW compiler toolchain. Now BIBTOOL_DEFAULT is built mainly from LIBDIR which in turn should be `/usr/local/lib/BibTool`. Now the `/usr/local` part is somehow replaced with `C:\Users\L...\opt\msys64\mingw64` along the way and that is not a valid path string in C. I can't really pin down where it is changed though.

**Comment by ge-ne** [comment]
Well you could try to set he environment variable manually before compiling or in the makefile.
Just an idea...

**Comment by fleimgruber** [comment]
It turns out that this works on the "MSYS2 MSYS" shell but not on the "MSYS2 MinGW 64-bit" shell. I tried with the 64 bit first out of habit. For me this is solved, I don't think it really warrants addition to docs, WDYT?
