### ISSUE TITLE
Release version 2.68 to avoid users from running into fixed issues

### ISSUE THREAD

**Issue by joe4dev** [ge-ne/bibtool#67]
Users run into unnecessary problems that were actually fixed but not yet "released" because they download/compile older code:
For example, `bibtool  -x myfile.aux` is broken in 2.67 but actually fixed in HEAD: https://tex.stackexchange.com/questions/499320/problem-with-bibtool-when-extracting-bibliography-information-from-an-aux-file-i
Currently, even users following the download instructions on Github will get an outdated version (e.g., from CTAN or your website).

At least officially tagging it on Github would make it more convenient to install (e.g., through Homebrew).

**Comment by ge-ne** [comment]
done
