### ISSUE TITLE
2.68 release is missing in GitHub releases

### ISSUE THREAD

**Issue by mjg** [ge-ne/bibtool#69]
The title says it all :)

GitHub releases is what I'm following as the Fedora packager for BibTool. I don't mind switching to the website downloads if those are considered the primary source. In any case I check the signatures.

**Comment by ge-ne** [comment]
Thanks for the reminder. I must have been too tired yesterday to find the respective button:-(

In any case the following three locations should be in sync for releases:
- my private website
- CTAN
- GitHub
