### ISSUE TITLE
unlimited line width

### ISSUE THREAD

**Issue by thorade** [ge-ne/bibtool#7]
This is a personal choice and I know not everybody follows it, 
but I prefer to have unlimited line width, ensuring one field per line. 
My editor does line breaks dynamically.

Would it be possible to add support for unlimited line width?
Zero or negative values could be used to indicate unlimited line width,
i.e. `--print.line.length=0` really means `--print.line.length=∞`

**Comment by ge-ne** [comment]
You could use something like --print.line.length=99999 which is -- for practical purposes -- as good as a special treatment of negative values. Indeed I had the need for single line entries myself and did the same thing.
I will put it on my list, but with rather low priority

**Comment by thorade** [comment]
Yes, I do also use 99999 or similar right now so this suggestion has very low priority,
on the other hand the implementation would be quite easy, 
just using the highest allowed integer when a zero is found.
Thanks!

**Comment by thorade** [comment]
Marked as wontfix, and a workaround exists.
