### ISSUE TITLE
feature: input BibLaTeX output BibTeX

### ISSUE THREAD

**Issue by GeoBosh** [ge-ne/bibtool#75]
In some use scenarios it is helpful to convert `BibLaTeX` files to  `BibTeX` (eg a journal citation style may require that). Assuming that it is ok to keep UTF-8 encoding, if present, is it feasible to achieve a reasonable conversion quality with the facilities offered by Bibtool?

**Comment by ge-ne** [comment]
BibLaTeX and BibTeX share essentially the same file format. BibTool has been written to process this format. At first sight BibTool is capable to perform the task you depiced. You have to write a resource file where you define how you expect the conversion to be performed.

**Comment by GeoBosh** [comment]
Indeed, I wonder if somebody has written such a file, i.e. one that produces a BibTeX file for processors that are unaware of BibLaTeX. Some of it is straightforward translation of `journaltitle` to `journal`,`date` to `year` and similar, but there are intricacies which add up and not worth the trouble iif somebody has put the effort to go through them.
