### ISSUE TITLE
Feature request: print.align = minimal

### ISSUE THREAD

**Issue by bersbersbers** [ge-ne/bibtool#80]
I'd like some form of
```
print.align = minimal
```
in order to obtain this (note different alignments for different entry types):

```
@article{Godinez2017,
  author  = {Auth},
  journal = journal,
}

@inproceedings{Zhang2017,
  author    = {Auth},
  booktitle = book,
}
```

**Comment by ge-ne** [comment]
I see what you are after. But the name is misleading. If you really want to have it minima then you can set

print.align{1}

This eliminates any white-space around the equals sign.

**Comment by bersbersbers** [comment]
Well, yes and no: first, I see that `minimal` can be misleading. But that is true for other things, too:

To my understanding, `print.align{1}` does not necessarily "align" things, because every `=` is pushed right by its field name.

In the ideal world (I am aware of backward-compatibility issues - just brainstorming), one might rename the setting to something like `print.equalsign.position`. Then:

- Current (numeric) settings would keep their meaning.
- `minimal` would mean you say (what is currently `print.align{1}`). An alias could be `align-per-field`.
- What I am looking for could be `align-per-entry`.
- One could have an `align-per-file`, which is close to how it currently works, just with an minimal number to align all equals signs throughout the whole file. (The problem with this one is that it is not source-control stable: adding a single entry with a longer field name would add spaces throughout the whole document, enlarging diffs unnecessarily.)

Spaces around `=` could be taken into account manually, but I prefer having them.

**Comment by ge-ne** [comment]
I am thinking about a minimal invasive solution. I might add
```
print.align{auto}
```
This would determine the minimal width per entry -- not per entry type.
Thus is not very source-control friendly. But it will not be the default in any way.

The spaces around = can already be achieved with the boolean resource `print.wide.equal`.

**Comment by bersbersbers** [comment]
> I am thinking about a minimal invasive solution. I might add
> ```
> print.align{auto}
> ```
> This would determine the minimal width per entry -- not per entry type.

It wasn't obvious from my example, but that's exactly what I was thinking about: indentation for each entry based on the length of the longest field in this specific entry. So two @article's can have different indentations if one has a publisher and the other does not.

> Thus is not very source-control friendly.

True, if you think about adding fields to an entry. But that happens rarely. I was mainly concerned about stability when adding new entries, and your solution is stable in this setting, if I understand you correctly.

> The spaces around = can already be achieved with the boolean resource `print.wide.equal`.

Ah, I see. Thanks!

**Comment by ge-ne** [comment]
Implemented. It will make it into the next release.
