### ISSUE TITLE
entry type @manuscript

### ISSUE THREAD

**Issue by tutebatti** [ge-ne/bibtool#82]
Hello,
the bibstyle "biblatex-manuscripts-philology" (https://ctan.org/pkg/biblatex-manuscripts-philology?lang=de) adds the type @manuscript.
Can this be included?
Thank you!

**Comment by ge-ne** [comment]
Yes. See resources new.entry.type and new.field.type in the documentation and biblatex.rsc in the library for examples.

**Comment by tutebatti** [comment]
Thank you!
