### ISSUE TITLE
How to convert biblatex bib file to bibtex bib file

### ISSUE THREAD

**Issue by benibilme** [ge-ne/bibtool#83]
Hello,

I have read the manual but I have not been able to find a clear example for conversion between biblatex and bibtex file formats. Is this possible with bibtool?  It seems, it can do it but I have not been able to see that.  

I appreciate if you can provide a  sample command to achieve that. 

Thanks in advance

**Comment by ge-ne** [comment]
bibLaTeX and BibTeX share essentially the same syntax of the
bibliography files. The difference are the bibstyles you are
using. And here things are start to be real work.

You can have a look at the files lib/keep_biblatex.rsc and
lib/keep_bib.rsc in BibTool to see the entry types and fields
supported by the default bibstyles. Now you need to define
rewrite.rules in BibTool to shuffle the contents of one field to
another or to change the entry type until things fit.

It can be done. But nearly nobody will need it in this generality.  I
would start by analyzing the biblatex file and just define those rules
required by the source file. This can also take into account the "bad
habits" of the original author -- i.e. abusing fields for something
else or using non-standard fields.

As a starting point I would include biblatex.rsc to have all fields
and item types defined. Then rewrite rules like in lib/improve.rsc
have to be written to do the job.

Good luck with this endeavour.
(I guess you have good reasons for it;-)

**Comment by benibilme** [comment]
Hello,

Thank you for the response. Sorry for responding late. I encountered this tool while searching a way to convert a biblatex bib file to bibtex bib file. I need to submit an article written with biblatex to a journal which accepts bibtex. It seems too much hassle which exceeds my latex knowledge and wish. It will be easier to simply find the articles and get bibtex references. Thank you anyway.  Is  there any tool that you know which can do this?

**Comment by ge-ne** [comment]
Hi,
In this case I would recommend to do it manually. To start with you could simply try to use your BibLaTeX file with the BibTeX style provided by the journal. If something is missing or wrong in the output then adjust the type or field of the respective item.
Hope this helps

**Comment by stefanhusmann** [comment]
benibilme ***@***.***> writes:

> Hello,
>
> Thank you for the response. Sorry for responding late. I encountered this tool while searching a way to convert a biblatex bib file to bibtex bib file. I
> need to submit an article written with biblatex to a journal which accepts bibtex. It seems too much hassle which exceeds my latex knowledge and
> wish. It will be easier to simply find the articles and get bibtex references. Thank you anyway. Is there any tool that you know which can do this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Hello,

maybe you want to look at bibutils.

http://sourceforge.net/p/bibutils/home/Bibutils

Bast Regards
Stefan
