### ISSUE TITLE
BibTool ERROR (line 98 in ./vueandpandoc-v1.0.1.bib): Unknown entry type

### ISSUE THREAD

**Issue by crguezl** [ge-ne/bibtool#85]
@ge-ne @kiryph @jgmbenoit 

Many thanks for bibtool.

bibtool doesn't know about `software` entries. When given as input something like:

```bib
@software{casiano_rodriguez_leon_2021_5771502,
  author       = {Casiano Rodriguez-Leon},
  title        = {{crguezl/learning-vue-geting-started-guide: 
                   Annotated Reading of the Essentials Section of the
                   Vue.js Guide}},
  month        = dec,
  year         = 2021,
  publisher    = {Zenodo},
  version      = {v1.0.0},
  doi          = {10.5281/zenodo.5771502},
  url          = {https://doi.org/10.5281/zenodo.5771502}
}
```

complains with an error message:

``` 
$ bibtool -K -d *.bib -o single.bib


@software{casiano_rodriguez_leon_2021_5771502,
_^
*** BibTool ERROR (line 98 in ./vueandpandoc-v1.0.1.bib): Unknown entry type

*** BibTool WARNING: Skipping to next '@'
```

**Comment by ge-ne** [comment]
Right. As documented just the entries known by BibTeX are known per default.
If ou want to have the ebtry types known to BibLaTeX you can interagte the library biblatex with the command line option "-r biblatex" of integrate the definition(s) into your resource file.

**Comment by ge-ne** [comment]
Right. As documented just the entries known by BibTeX are known per default.
If ou want to have the ebtry types known to BibLaTeX you can interagte the library biblatex with the command line option "-r biblatex" of integrate the definition(s) into your resource file.
